/*
 * LDPC parity-check matrix for Mercury modem
 * Rate 12/16 (K=1200, P=400, N=1600)
 * Generated by tools/generate_ldpc_12_16.py
 * PEG algorithm with IRA accumulator structure
 */

#ifndef MERCURY_NORMAL_12_16_H
#define MERCURY_NORMAL_12_16_H

extern int mercury_normal_Cwidth_12_16;
extern int mercury_normal_Vwidth_12_16;
extern int mercury_normal_dwidth_12_16;

extern int mercury_normal_QCmatrixC_12_16[400][14];
extern int mercury_normal_QCmatrixEnc_12_16[400][13];
extern int mercury_normal_QCmatrixV_12_16[1600][6];
extern int mercury_normal_QCmatrixd_12_16[10];

#endif
