/*
 * LDPC parity-check matrix for Mercury modem
 * Rate 10/16 (K=1000, P=600, N=1600)
 * Generated by tools/generate_ldpc_10_16.py
 * PEG algorithm with IRA accumulator structure
 */

#ifndef MERCURY_NORMAL_10_16_H
#define MERCURY_NORMAL_10_16_H

extern int mercury_normal_Cwidth_10_16;
extern int mercury_normal_Vwidth_10_16;
extern int mercury_normal_dwidth_10_16;

extern int mercury_normal_QCmatrixC_10_16[600][9];
extern int mercury_normal_QCmatrixEnc_10_16[600][8];
extern int mercury_normal_QCmatrixV_10_16[1600][6];
extern int mercury_normal_QCmatrixd_10_16[10];

#endif
