#!/usr/bin/env python3
"""Pack web/ into a C source implementing Mongoose's packed-filesystem hooks.

Run at BUILD time, never checked in: a generated file in the tree drifts
silently from the pages it is generated from, and the whole point here is that
the served UI cannot disagree with the shipped one.

Emits mg_unpack()/mg_unlist(), which mongoose calls when built with
MG_ENABLE_PACKED_FS=1.  Paths are exposed under /web so the HTTP handler can
point root_dir at it exactly as it did at the on-disk directory.
"""
import os, sys

def main(srcdir, out):
    files = sorted(f for f in os.listdir(srcdir)
                   if os.path.isfile(os.path.join(srcdir, f)))
    w = ['/* Generated by pack_web.py - do not edit, do not commit. */',
         '#include <stddef.h>', '#include <time.h>', '']
    names = []
    for i, f in enumerate(files):
        data = open(os.path.join(srcdir, f), 'rb').read()
        sym = 'f%d' % i
        names.append(('/web/' + f, sym, len(data)))
        body = ','.join(str(b) for b in data)
        w.append('static const unsigned char %s[] = {%s,0};' % (sym, body))
    w.append('')
    w.append('static const struct {const char *n; const unsigned char *d; size_t s;} tab[] = {')
    for path, sym, size in names:
        w.append('  {"%s", %s, %d},' % (path, sym, size))
    w.append('  {NULL, NULL, 0}')
    w.append('};')
    w.append('''
const char *mg_unpack(const char *path, size_t *size, time_t *mtime) {
  for (int i = 0; tab[i].n != NULL; i++) {
    if (strcmp(path, tab[i].n) == 0) {
      if (size) *size = tab[i].s;
      if (mtime) *mtime = 0;
      return (const char *) tab[i].d;
    }
  }
  if (size) *size = 0;
  if (mtime) *mtime = 0;
  return NULL;
}

const char *mg_unlist(size_t no) {
  size_t n = 0;
  for (int i = 0; tab[i].n != NULL; i++, n++)
    if (n == no) return tab[i].n;
  return NULL;
}''')
    w.insert(2, '#include <string.h>')
    open(out, 'w').write('\n'.join(w) + '\n')
    total = sum(s for _, _, s in names)
    print('packed %d files, %d bytes -> %s' % (len(names), total, out))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
