#!/bin/sh
# Pack web/ into a C source implementing mongoose's packed-filesystem hooks.
#
# usage: pack_web.sh SRCDIR OUTFILE
#
# POSIX sh + od + tr only.  Deliberately no python/perl/xxd: this runs inside
# every cross-compile container we build in, and the Windows x64 image has no
# python3 at all -- a generator that needs one turns a UI change into a broken
# build on one target only (issue #204 follow-up).
set -e

src=$1
out=$2
[ -n "$src" ] && [ -n "$out" ] || { echo "usage: $0 SRCDIR OUTFILE" >&2; exit 1; }

# Both loops below must walk the files in the SAME order; they use the same glob.
{
    echo '/* Generated by pack_web.sh at build time - do not edit, do not commit. */'
    echo '#include <stddef.h>'
    echo '#include <string.h>'
    echo '#include <time.h>'
    echo

    i=0
    for f in "$src"/*; do
        [ -f "$f" ] || continue
        printf 'static const unsigned char f%d[] = {' "$i"
        od -An -v -tu1 < "$f" | tr -s ' ' '\n' | grep -v '^$' | tr '\n' ','
        printf '0};\n'
        i=$((i + 1))
    done

    echo
    echo 'static const struct { const char *n; const unsigned char *d; size_t s; } tab[] = {'
    i=0
    for f in "$src"/*; do
        [ -f "$f" ] || continue
        b=`basename "$f"`
        sz=`wc -c < "$f" | tr -d ' '`
        printf '  {"/web/%s", f%d, %s},\n' "$b" "$i" "$sz"
        i=$((i + 1))
    done
    echo '  {NULL, NULL, 0}'
    echo '};'

    cat <<'CEOF'

const char *mg_unpack(const char *path, size_t *size, time_t *mtime) {
  int i;
  for (i = 0; tab[i].n != NULL; i++) {
    if (strcmp(path, tab[i].n) == 0) {
      if (size != NULL) *size = tab[i].s;
      if (mtime != NULL) *mtime = 0;
      return (const char *) tab[i].d;
    }
  }
  if (size != NULL) *size = 0;
  if (mtime != NULL) *mtime = 0;
  return NULL;
}

const char *mg_unlist(size_t no) {
  size_t n = 0;
  int i;
  for (i = 0; tab[i].n != NULL; i++, n++)
    if (n == no) return tab[i].n;
  return NULL;
}
CEOF
} > "$out"
